import Header from "@/components/Header/Header";
import type { Metadata } from "next";
import './globals.css';

export const metadata: Metadata = {
  title: {
    template: "Mahdi | %s",
    default: "Mahdi",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
